def build_guideline_context(patient, predictions):

    guidance = []

    age = patient.get("age")
    nihss = patient.get("baseline_nihss")
    sbp = patient.get("systolic_bp")
    glucose = patient.get("glucose")
    aspects = patient.get("aspects")

    ivt = patient.get("iv_thrombolysis", 0)
    evt = patient.get("mechanical_thrombectomy", 0)

    ht = patient.get("hemorrhagic_transformation")
    sich = patient.get("symptomatic_ich")

    # =========================================================
    # BLOOD PRESSURE
    # =========================================================

    if sbp is not None:

        guidance.append({
            "domain": "Blood pressure",
            "patient_value": f"SBP {sbp} mmHg",
            "guideline_context":
                "Blood pressure management should be interpreted "
                "according to reperfusion treatment status and the "
                "individual clinical context."
        })

        if evt == 1:
            guidance.append({
                "domain": "Post-EVT blood pressure",
                "patient_value": f"SBP {sbp} mmHg",
                "guideline_context":
                    "The 2026 AHA/ASA guideline does not recommend "
                    "intensive systolic blood pressure reduction to "
                    "<140 mmHg after successful EVT solely to improve "
                    "functional outcome."
            })

    # =========================================================
    # GLUCOSE
    # =========================================================

    if glucose is not None:

        guidance.append({
            "domain": "Glucose",
            "patient_value": f"{glucose} mg/dL",
            "guideline_context":
                "Avoid assuming that intensive glucose lowering to "
                "80–130 mg/dL improves functional outcome. The "
                "guideline reports no functional benefit and an "
                "increased risk of severe hypoglycemia."
        })

    # =========================================================
    # REPERFUSION
    # =========================================================

    if ivt == 1:

        guidance.append({
            "domain": "IV thrombolysis",
            "patient_value": "IV thrombolysis recorded",
            "guideline_context":
                "Interpret subsequent monitoring and recommendations "
                "in the context of thrombolytic treatment."
        })

    if evt == 1:

        guidance.append({
            "domain": "Endovascular thrombectomy",
            "patient_value": "EVT recorded",
            "guideline_context":
                "Interpret subsequent neurological and hemodynamic "
                "monitoring in the context of EVT and reperfusion status."
        })

    # =========================================================
    # HEMORRHAGIC TRANSFORMATION
    # =========================================================

    if ht == 1:

        guidance.append({
            "domain": "Hemorrhagic transformation",
            "patient_value": "Observed",
            "guideline_context":
                "Hemorrhagic transformation is now an observed "
                "clinical event rather than only a predicted risk. "
                "Escalate the output for clinician assessment rather "
                "than treating the earlier HT probability as the "
                "current outcome."
        })

    if sich == 1:

        guidance.append({
            "domain": "Symptomatic intracranial hemorrhage",
            "patient_value": "Observed",
            "guideline_context":
                "This represents an important acute complication and "
                "should be prominently surfaced for clinician review."
        })

    # =========================================================
    # MODEL INTELLIGENCE
    # =========================================================

    ht_probability = (
        predictions
        .get("treatment", {})
        .get("ht_probability")
        if predictions else None
    )

    if ht_probability is not None:

        guidance.append({
            "domain": "AI-predicted HT risk",
            "patient_value":
                f"{ht_probability:.1%}",
            "guideline_context":
                "This value is generated by the AdaptStroke predictive "
                "model and is not itself an AHA/ASA guideline "
                "recommendation."
        })

    return guidance